// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Income struct {
	ID        uuid.UUID   `json:"id"`
	Payee     string      `json:"payee"`
	Balance   float32     `json:"balance"`
	ProjectID pgtype.UUID `json:"project_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Loan struct {
	ID        uuid.UUID `json:"id"`
	Borrower  string    `json:"borrower"`
	Balance   float32   `json:"balance"`
	Subject   string    `json:"subject"`
	CreatedAt time.Time `json:"created_at"`
	UpdateAt  time.Time `json:"update_at"`
}

type PayOut struct {
	ID        uuid.UUID `json:"id"`
	Owner     string    `json:"owner"`
	Balance   float32   `json:"balance"`
	Subject   string    `json:"subject"`
	CreatedAt time.Time `json:"created_at"`
	UpdateAt  time.Time `json:"update_at"`
}

type Project struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Balance     float32   `json:"balance"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
