// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreatePayOut(ctx context.Context, arg CreatePayOutParams) (PayOut, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteIncome(ctx context.Context, id string) (Income, error)
	DeleteLoan(ctx context.Context, id string) (Loan, error)
	DeletePayOut(ctx context.Context, id string) (PayOut, error)
	DeleteProject(ctx context.Context, id string) (Project, error)
	GetIncome(ctx context.Context, id string) (Income, error)
	GetLoan(ctx context.Context, id string) (Loan, error)
	GetPayOut(ctx context.Context, id string) (PayOut, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListIncomes(ctx context.Context, arg ListIncomesParams) ([]Income, error)
	ListLoans(ctx context.Context, arg ListLoansParams) ([]Loan, error)
	ListPayOuts(ctx context.Context, arg ListPayOutsParams) ([]PayOut, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	SearchIncomes(ctx context.Context, arg SearchIncomesParams) ([]Income, error)
	SearchLoans(ctx context.Context, arg SearchLoansParams) ([]Loan, error)
	SearchPayOuts(ctx context.Context, arg SearchPayOutsParams) ([]PayOut, error)
	SearchProjects(ctx context.Context, arg SearchProjectsParams) ([]Project, error)
}

var _ Querier = (*Queries)(nil)
