---
loglevel: info
logfile: logs/plam.log
database:
  driverName: postgresql
  dataSourceName: postgresql://myuser:mypass@localhost:5432/mydb?sslmode=disable
  migrationURL: file://db/migration
server:
  serverAddress: :8080
  tokenSymmetricKey: 51127a1bebd577a85d4c8744e7c8aab4
  accessTokenDuration: 12h
